version: "3"
services:
  webserver:
    depends_on:
      - database
    # General purpose PHP image 
    # (Note: This image is based on https://hub.docker.com/r/thecodingmachine/php)
    image: johndifool/php:7.4-v4-apache-public
    # Activate portmapping for standalone usage, i.e. without nginx proxy
    #ports:
    #  - "80:80"
    #  - "443:443"
    volumes:
      - ./conf/apache/my-apache.conf:/etc/apache2/conf-enabled/my-apache.conf
      - ./src:/var/www/html
    networks:
      # allow communication with nginx proxy
      - dev
      # internal network to allow communication between services of this container
      - default
    environment:
      # The host your app is accessible at.
      # (Don't forget to add an entry in your hosts /etc/hosts file.)
      - VIRTUAL_HOST=php74-example-app.local
      #- PHP_EXTENSION_XDEBUG=1
  database:
    # Use whatever database server and version you need
    image: mysql:5.7
    ports: 
      # Exposes port 3306 with a 33306 on the host port. 
      # (Note: By doing this you are responsible for managing port collisions.
      #        Meaning, choose a unique port for every database service across all projects.)
      - "33306:3306"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    environment:
      - "MYSQL_USER=${MYSQL_USER:-db_usr}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD:-p4ssw0rd}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE:-db_app}"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    volumes:
      # Initializing container with this data, when started for the first time.
      #- ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      # This is, where your database data goes.
      - ./db:/var/lib/mysql  
    networks:
      # internal network to allow communication between services of this container
      - default
networks:
  # allow communication with nginx proxy
  dev:
    external: true
