version: "3"
services:
  app:
    depends_on:
      - database
    container_name: php74-example-app 
    # General purpose PHP image 
    # (Note: This image is based on https://hub.docker.com/r/thecodingmachine/php)
    image: johndifool/php:7.4-v4-apache-public
    volumes:
      - ./app:/var/www/html
    networks:
      - dev
    environment:
      # The host your app is accessible at.
      # (Don't forget to add an entry in your hosts /etc/hosts file.)
      - VIRTUAL_HOST=php74-example-app.local
      #- PHP_EXTENSION_XDEBUG=1
  database:
    container_name: php74-example-db 
    # Use whatever database server and version you need
    image: mysql:5.6
    ports: 
      # Exposes port 3306 with a 33306 on the host port. 
      # (Note by doing this you are responsible for managing port collisions`.)
      - "33306:3306"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    environment:
      - "MYSQL_USER=${MYSQL_USER:-app_usr}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE:-app_db}"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    volumes:
      - ./db:/var/lib/mysql  
    networks:
      - dev
networks:
  dev:
    external: true
