version: "3"
services:
  app:
    depends_on:
      - database
    # General purpose PHP image 
    # (Note: This image is based on https://hub.docker.com/r/thecodingmachine/php)
    image: johndifool/php:7.4-v4-apache-public
    volumes:
      - ./conf/apache/my-apache.conf:/etc/apache2/conf-enabled/my-apache.conf
      - ./www/html:/var/www/html
    networks:
      - dev
      - default
    environment:
      # The host your app is accessible at.
      # (Don't forget to add an entry in your hosts /etc/hosts file.)
      - VIRTUAL_HOST=php74-example-app.local
      #- PHP_EXTENSION_XDEBUG=1
  database:
    # Use whatever database server and version you need
    image: mysql:5.7
    ports: 
      # Exposes port 3306 with a 33306 on the host port. 
      # (Note: By doing this you are responsible for managing port collisions.
      #        Meaning, choose a unique port for every database service across all projects.)
      - "33306:3306"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    environment:
      - "MYSQL_USER=${MYSQL_USER:-app_usr}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD:-p4ssw0rd}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE:-app_db}"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    volumes:
      - ./db:/var/lib/mysql  
    networks:
      - dev
      - default
networks:
  dev:
    external: true
