version: '2'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./conf/my-nginx.conf:/etc/nginx/conf.d/my-nginx.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
networks:
  default:
    name: dev
